### PR TITLE
Expose the interface to Window and Worker

### PR DESCRIPTION
**Pull request by plehegar**

### CODE REVIEW

**Comment by igrigorik** [comment]
:+1:

**Comment by igrigorik** [comment]
Hmm, hit the merge button.. and then started thinking (I know, I know): worker doesn't need Nav timing, since everything looks like a resource fetch to it. Do we need this? Should I revert?

**Comment by toddreifsteck** [comment]
I believe it should be reverted and this issue closed. The default exposure is the default global aka Window and thus we should not need to explicitly Expose this (http://heycam.github.io/webidl/#Exposed).

**Comment by plehegar** [comment]
Reverted #26

**Comment by igrigorik** [comment]
Thanks, apologies about the extra work.

**Pull request merged**
