### PR TITLE
secureConnectionStart is mandatory resource-timing/issues/16

### PR DESCRIPTION
**Pull request by plehegar**

### CODE REVIEW

**Comment by igrigorik** [comment]
Same comment as https://github.com/w3c/resource-timing/pull/24#discussion_r31670918. That said, it's a separate issue.

lgtm.

**Comment by plehegar** [comment]
@toddreifsteck this one will need a +1 from you

**Comment by plehegar** [comment]
(Todd approved the one for resource timing, so I assume this one is fine as well)

**Comment by toddreifsteck** [comment]
Thanks!

Sent from my Windows Phone
________________________________

**Pull request merged**
