### PR TITLE
set name to document address

### LINKED ISSUE #59: Report URL in "name" attribute (instead of "document")
NT2 "name" attribute is currently set to "document".
Should this be set to the URL instead (as in RT2) ?
Related discussion in: https://crbug.com/675039

### PR DESCRIPTION
**Pull request by igrigorik**
Closes #59.

@toddreifsteck @plehegar ptal.

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/navigation-timing/name-address.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/navigation-timing/31d9870...a59900b.html)

### CODE REVIEW

**Comment by igrigorik** [comment]
@spanicker any updates on this / feedback from the field?

**Comment by spanicker** [comment]
re: feedback from field - I haven't heard anything.

**Comment by toddreifsteck** [comment]
The spec update LGTM. Do we have a test PR to go along with it?

**Comment by igrigorik** [comment]
@toddreifsteck tests already landed in https://github.com/w3c/web-platform-tests/commit/d24a86b138b2074f32a6f2bbd6ca5de445259dd3.

**Pull request merged**
