### PR TITLE
updated timing attributes diagram

### LINKED ISSUE #44: Processing Model chart is missing domLoading marker
Processing model chart - https://w3c.github.io/navigation-timing/#processing-model - is missing a marker for domLoading.

### PR DESCRIPTION
**Pull request by igrigorik**
Preview: https://cdn.rawgit.com/w3c/navigation-timing/update-diagram/index.html#process

- show attributes defined by Resource Timing L2
- link to source

Closes #44.

### CODE REVIEW

**Comment by yoavweiss** [comment]
Looks good. Any particular reason you removed the comment on the possibility of "non-normative intervals" between measurements? (If this is not something we actually see in practice, I agree that it can be removed, just missed the discussion)

**Comment by igrigorik** [comment]
"Not something we actually see in practice" -- that. I think it goes without saying that UA can interleave other work, I don't think we need to call that out.

**Comment by yoavweiss** [comment]
OK, LGTM! :)

**Comment by toddreifsteck** [comment]
LGTM! Merging

**Pull request merged**
