### PR TITLE
editorial: use absolute URL for svg image

### PR DESCRIPTION
**Pull request by marcoscaceres**
Merge me first :) Then we can verify the link checker is working.

***
[Preview](https://s3.amazonaws.com/pr-preview/marcoscaceres/navigation-timing/link_image.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/navigation-timing/31d9870...marcoscaceres:9024a3c.html)

### CODE REVIEW

**Comment by igrigorik** [comment]
Curious, why does it need to be absolute? If we ever need to iterate on the file.. previews become a lot harder =/

**Comment by marcoscaceres** [comment]
@igrigorik, it's because the generated spec is passed to the link checker, but then the link checker doesn't know what to "base" that URL off (so it does it off the generated spec's URL... which results in a 404).

**Comment by marcoscaceres** [comment]
It's the unfortunate tradeoff we need to make for the link checking to work. Having said that, diagrams in specs rarely change in my experience (maybe once a year, at most).

**Comment by igrigorik** [comment]
Can we teach the link-checker to use the base of the document? Or is that an uphill battle? :)

**Comment by marcoscaceres** [comment]
I think that's a big ask... the link checker is some insane legacy piece of machinery from the 90's... but @dontcallmedom would know.

**Comment by dontcallmedom** [comment]
@marcoscaceres the command-line linkchecker has a `--masquerade` option that allows to replace a base URL with another - probably helpful here (although I'm not sure how you're using the linkchecker here)

**Comment by marcoscaceres** [comment]
I think I'll just need to bite the bullet and do this using a headless browser. Because of recent changes to the (WHATWG) HTML spec, the link checker is now too limited to be of value.

**Comment by marcoscaceres** [comment]
(I'm not promising to do it any time soon tho - it's not a lot of work, but would probably take about 1-2 weeks to do... be nice as an internship project)

**Pull request closed without merging**
